import sys

# Add project root to path if needed
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "galaxy_ng.settings")
from django.conf import settingsimport pytest
import os
import sys
import pytest
from django.core.management import call_command
from galaxy_ng.app.models import CollectionRemote, AnsibleRepository
from galaxy_ng.app.utils.galaxy import upstream_collection_iterator
from galaxy_ng.app.management.commands.sync_galaxy_collections import Command
from pulp_ansible.app.models import CollectionVersion
from pulp_ansible.app.models import CollectionRemote as PulpCollectionRemote
from pulp_ansible.app.models import AnsibleRepository as PulpAnsibleRepository
from pulpcore.plugin.tasking import dispatch
from pulpcore.plugin.constants import TASK_FINAL_STATES, TASK_STATES
from pulpcore.plugin.models import Task

@pytest.fixture
def create_collection_remote():
    remote = PulpCollectionRemote.objects.create(name='test-remote')
    return remote

@pytest.fixture
def create_ansible_repository():
    repository = PulpAnsibleRepository.objects.create(name='test-repo')
    return repository

@pytest.fixture
def create_collection_version():
    collection_version = CollectionVersion.objects.create(
        namespace='test-namespace',
        name='test-name',
        version='1.0.0',
        contents='test-contents',
        requires_ansible='test-requirements'
    )
    return collection_version

@pytest.fixture
def create_task():
    task = Task.objects.create(
        state=TASK_STATES.PENDING,
        error=None,
        result=None,
        created=None,
        updated=None,
        user=None,
        exclusive_resources=None,
        related_resources=None,
        resource_version=None,
        resource_type=None,
        resource_pk=None,
        resource_name=None,
        resource_href=None,
        task_group=None,
        task_group_href=None,
        task_group_name=None,
        task_group_pk=None,
        task_group_resource=None,
        task_group_resource_href=None,
        task_group_resource_name=None,
        task_group_resource_pk=None,
        task_group_resource_version=None,
        task_group_resource_type=None,
        task_group_resource_created=None,
        task_group_resource_updated=None,
        task_group_resource_error=None,
        task_group_resource_result=None,
        task_group_resource_state=None,
        task_group_resource_exclusive_resources=None,
        task_group_resource_related_resources=None,
        task_group_resource_resource_version=None,
        task_group_resource_resource_type=None,
        task_group_resource_resource_pk=None,
        task_group_resource_resource_name=None,
        task_group_resource_resource_href=None,
        task_group_resource_resource_created=None,
        task_group_resource_resource_updated=None,
        task_group_resource_resource_error=None,
        task_group_resource_resource_result=None,
        task_group_resource_resource_state=None,
        task_group_resource_resource_exclusive_resources=None,
        task_group_resource_resource_related_resources=None,
        task_group_resource_resource_resource_version=None,
        task_group_resource_resource_resource_type=None,
        task_group_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_name=None,
        task_group_resource_resource_resource_href=None,
        task_group_resource_resource_resource_created=None,
        task_group_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_error=None,
        task_group_resource_resource_resource_result=None,
        task_group_resource_resource_resource_state=None,
        task_group_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_related_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_version=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_type=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_pk=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_name=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_href=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_created=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_updated=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_error=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_result=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_state=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource_exclusive_resources=None,
        task_group_resource_resource_resource_resource_resource_resource_resource_resource_resource_resource