name: test shiki

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags (needed for SonarQube)
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libsasl2-dev libldap2-dev libssl-dev gettext
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install tox coverage[toml]
          
          # Install requirements files that exist
          for req_file in dev_requirements.txt unittest_requirements.txt lint_requirements.txt; do
            if [ -f "$req_file" ]; then
              echo "Installing dependencies from $req_file"
              pip install -r "$req_file" || echo "Warning: Some packages in $req_file failed to install"
            fi
          done
          
          # Install the package in development mode
          pip install -e .
      
      - name: Run tests with coverage
        run: |
          # Run tests with tox
          tox --colored yes -e py311 || true
          
          # If PR number is available, inject it into coverage.xml
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            sed -i '2i <!-- PR ${{ github.event.number }} -->' coverage.xml
          fi
          
          # Make sure coverage.xml exists
          if [ ! -f coverage.xml ]; then
            echo "<?xml version='1.0' encoding='UTF-8'?><coverage></coverage>" > coverage.xml
          fi
      
      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
          retention-days: 1